# **CYBER THREAT ANALYTICS DASHBOARD FOR A CORPORATE NETWORK**

#### Import libraries

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

#### Import raw data

In [4]:
df = pd.read_csv("cyber.csv")

#### Sample data

In [7]:
df.head(20)

,Incident_ID,Date_Repoted,Threat_Typ,Severtiy,Departmnt,Source_Country,Detected_By,Failed_Logins,MTTD_minutes,MTTR_hours,Status
0,INC1124,2025-07-17,Phishing,Critical,NaN,Russia,Firewall,259,18,3.46,Investigating
1,INC1062,2025-06-11,Ransomware,Medium,IT,Unknown,SIEM,405,33,9.37,Investigating
2,INC1098,2025-04-23,Phishing,Low,Sales,Germany,Firewall,421,68,7.65,Investigating
3,INC1023,2025-04-25,Ransomware,Low,IT,NaN,Manual,395,48,4.83,Open
4,INC1152,2025-05-04,Malware,High,Finance,China,SIEM,210,112,7.19,Resolved
5,INC1013,2025-01-25,Malware,Low,Finance,India,Firewall,71,54,7.15,Open
6,INC1133,2025-04-01,Phishing,Critical,HR,Germany,Antivirus,76,78,10.87,Investigating
7,INC1150,2025-04-20,NaN,NaN,HR,USA,IDS,57,93,2.67,Resolved
8,INC1211,2025-03-24,Ransomware,Critical,Operations,NaN,Antivirus,56,83,7.61,Investigating
9,INC1145,2025-02-03,Malware,High,HR,Germany,Antivirus,36,87,0.85,Resolved
10,INC1028,2025-01-27,DDoS,High,HR,USA,Manual,398,88,7.72,Investigating
11,INC1030,2025-01-08,Intrusion,Low,IT,China,Antivirus,68,29,7.25,Investigating
12,INC1009,2025-05-01,Phishing,Critical,Sales,Unknown,Antivirus,448,25,5.49,Investigating
13,INC1218,2025-03-29,Phishing,Critical,NaN,India,Firewall,497,65,11.03,Investigating
14,INC1064,2025-03-17,DDoS,Medium,HR,India,Antivirus,313,85,5.86,Resolved
15,INC1140,2025-01-02,NaN,NaN,Operations,Brazil,Manual,75,63,2.06,Resolved
16,INC1094,2025-06-22,Malware,NaN,Finance,USA,IDS,279,101,1.67,Investigating
17,INC1093,2025-07-18,NaN,NaN,Operations,USA,IDS,126,35,3.19,Open
18,INC1111,2025-01-12,NaN,Medium,Finance,NaN,IDS,455,33,10.47,Open
19,INC1132,2025-05-28,Ransomware,Critical,Finance,India,Antivirus,2,75,2.14,Open

#### Size of data

In [14]:
print("Size of data :",df.shape)

Size of data : (235, 11)

#### Field Information

In [10]:
df.columns

Index(['Incident_ID', 'Date_Repoted', 'Threat_Typ', 'Severtiy', 'Departmnt',
       'Source_Country', 'Detected_By', 'Failed_Logins', 'MTTD_minutes',
       'MTTR_hours', 'Status'],
      dtype='object')

#### Data Types

In [15]:
df.dtypes

Incident_ID        object
Date_Repoted       object
Threat_Typ         object
Severtiy           object
Departmnt          object
Source_Country     object
Detected_By        object
Failed_Logins       int64
MTTD_minutes        int64
MTTR_hours        float64
Status             object
dtype: object

### DATA CLEANING

##### Column Names Correction

In [10]:
df= df.rename(columns={
    "Date_Repoted" : "Date_Reported",
    "Threat_Typ" : "Threat_Type",
    "Severtiy" : "Severity",
    "Departmnt" : "Department",
})

In [11]:
df.columns

Index(['Incident_ID', 'Date_Reported', 'Threat_Type', 'Severity', 'Department',
       'Source_Country', 'Detected_By', 'Failed_Logins', 'MTTD_minutes',
       'MTTR_hours', 'Status'],
      dtype='object')

##### Checking Null Values

In [12]:
print(df.isnull().sum())

Incident_ID        0
Date_Reported      0
Threat_Type       23
Severity          25
Department        23
Source_Country    23
Detected_By        0
Failed_Logins      0
MTTD_minutes       0
MTTR_hours         0
Status             0
dtype: int64

##### Handling Null Values

In [13]:
df["Threat_Type"] = df["Threat_Type"].fillna("Unknown")
df["Severity"] = df["Severity"].fillna("Unknown")
df["Department"] = df["Department"].fillna("Unknown")
df["Source_Country"] = df["Source_Country"].fillna("Unknown")

##### Checking Duplicate Values

In [16]:
df["Incident_ID"].duplicated().sum()

np.int64(15)

##### Handling Duplicate Values

In [17]:
df.drop_duplicates()

,Incident_ID,Date_Reported,Threat_Type,Severity,Department,Source_Country,Detected_By,Failed_Logins,MTTD_minutes,MTTR_hours,Status
0,INC1124,2025-07-17,Phishing,Critical,Unknown,Russia,Firewall,259,18,3.46,Investigating
1,INC1062,2025-06-11,Ransomware,Medium,IT,Unknown,SIEM,405,33,9.37,Investigating
2,INC1098,2025-04-23,Phishing,Low,Sales,Germany,Firewall,421,68,7.65,Investigating
3,INC1023,2025-04-25,Ransomware,Low,IT,Unknown,Manual,395,48,4.83,Open
4,INC1152,2025-05-04,Malware,High,Finance,China,SIEM,210,112,7.19,Resolved
...,...,...,...,...,...,...,...,...,...,...,...
230,INC1147,2025-07-19,Malware,Medium,Finance,China,SIEM,263,20,10.42,Open
231,INC1166,2025-06-09,DDoS,Low,Finance,USA,SIEM,140,80,10.20,Investigating
232,INC1180,2025-03-07,Ransomware,High,IT,Unknown,IDS,266,38,5.43,Resolved
233,INC1168,2025-03-26,Intrusion,High,Finance,Russia,Antivirus,94,15,9.12,Open
234,INC1184,2025-01-22,Intrusion,Critical,Finance,China,Antivirus,338,77,8.51,Investigating

### KPI REQUIREMENTS

In [32]:
#Total incident
Total_incident = df["Incident_ID"].count()

#Total Malware attack
Total_malware = (df["Threat_Type"]=="Malware").sum()

#Total Phishing attack
Total_phishing = (df["Threat_Type"]=="Phishing").sum()

#Total Intrusion attemps
Total_intrusion = (df["Threat_Type"]=="Intrusion").sum()

#Total Ransomware attack
Total_ransomware = (df["Threat_Type"]=="Ransomware").sum()

#Total failed login
Total_failed_login = df["Failed_Logins"].sum()

#High severity incident
high_severity_incident = (df["Severity"]=="High").sum()

#average of MTTD(mean time to detect)
avg_MTTD = (df["MTTD_minutes"].sum())/df["MTTD_minutes"].count()

#average of MTTR(mean time to respond)
avg_MTTR = (df["MTTR_hours"].sum())/df["MTTR_hours"].count()

#Total incident Resolved
Total_incident_resolve = (df["Status"]=="Resolved").sum()

# Display

print("Total Incident :",Total_incident)
print("Total Malware Attacks :",Total_malware)
print("Total Phishing Attacks :",Total_phishing)
print("Total Intrusion Attacks :",Total_intrusion)
print("Total Ransomware Attacks :",Total_ransomware)
print("Total failed logins :",Total_failed_login)
print("Total High severity incidents :",high_severity_incident)
print("Average of MTTD(mean to time detect) :",avg_MTTD)
print("Average of MTTR(mean to time respond) :",avg_MTTR)
print("Total Incident resolved :",Total_incident_resolve)

Total Incident : 235
Total Malware Attacks : 44
Total Phishing Attacks : 41
Total Intrusion Attacks : 49
Total Ransomware Attacks : 43
Total failed logins : 59854
Total High severity incidents : 55
Average of MTTD(mean to time detect) : 59.61276595744681
Average of MTTR(mean to time respond) : 6.433191489361702
Total Incident resolved : 77

### Downloading clean dataset

In [ ]:
df.to_csv(r"C:\Users\jeetendra\OneDrive\Desktop\cleaneddata.csv", index=False)